---
title: "Project1"
author: "Benson"
date: "2/27/2022"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
library(knitr)
```

## Data Import

using read.csv to read the data from txt file.

```{r DS}
chess_DS <- read.csv(file="https://raw.githubusercontent.com/Benson90/project1/main/project1.txt",head = TRUE, sep=",") 
#test reading file
chess_DS[1:9,]

```

## Retrive Information

- Seprate the 1st row data and 2nd row data into 2 dataframe.
- Transform the data into attributes. 
- Create a dataframe with Player’s Name, Player’s State, Total Number of Points, Player’s Pre-Rating, and Average Pre Chess Rating of Opponents
```{r retrieve}
chess_DS <- chess_DS[-c(1:3),]

firstrowdata <- chess_DS[seq(1, length(chess_DS),3)]

#test name
firstrowdata[1:6]

secondrowdata <- chess_DS[seq(2, length(chess_DS),3)]

#test status
secondrowdata[1:6]

#attributes for new dataframe
Players_Name <- str_trim(str_extract(firstrowdata,"(\\w+\\s){2,3}"))
Players_State <- str_extract(secondrowdata,"\\w+")
Total_Number_of_Points <- as.numeric(str_extract(firstrowdata, "\\d+\\.\\d+"))
Players_preRating <- as.integer(str_extract(str_extract(secondrowdata, "[^\\d]\\d{3,4}[^\\d]"),"\\d+"))


#calculate average rating
Pair <- as.integer(str_extract(firstrowdata, "\\d+"))
Opponent <- str_extract_all(str_extract_all(firstrowdata, "\\d+\\|"),"\\d+")
Average_preChess_Rating <- length(firstrowdata)
for(i in 1:length(firstrowdata)){
  Average_preChess_Rating[i] <- round(mean(Players_preRating[as.numeric(unlist(Opponent[Pair[i]]))]),digits = 0)
}

#new dataframe

NewDF <- data.frame(Players_Name,Players_State,Total_Number_of_Points,Players_preRating,Average_preChess_Rating)
NewDF

```

```{r test}


